### PR TITLE
HTML5 Validation & Persian Lang

### PR DESCRIPTION
**Pull request by cracki**
Add HTML5 Validation and Persian Language

### CODE REVIEW

**Comment by esroyo** [comment]
hi @cracki, thanks for your contribution :)
Just one suggestion:
what do you think about calling that new field "Required" and having its options be: ["Yes", "No"]
I think it might be better to reserve the word "Validation" for the future. For example, a field could be "required" and be "validated" by a regexp pattern. Do you agree?

**Comment by cracki** [comment]
yes i am agree. you are right ! :)

**Comment by esroyo** [comment]
great @cracki, I'll merge asap

**Comment by esroyo** [comment]
@cracki would you care telling me how you say "The field must be filled." in Persian? Thanks!

**Comment by cracki** [comment]
فیلد باید تکمیل شود

**Pull request merged**
